services:
  - type: web
    name: discord-channel-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_bot.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
